config/routes.rb
Rails.application.routes.draw do
  get 'grid/index'

  get 'modern6/index'

  get 'modern5/index'

  get 'modern4/index'

  get 'modern3/index'

  get 'modern2/index'

  get 'modern/index'

  get 'traditional/index'

  get 'page/index'

  root to: 'page#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grid_controller.rb
class GridController < ApplicationController
  layout 'grid'

  def index
  end
end

app/controllers/modern2_controller.rb
class Modern2Controller < ApplicationController
  layout 'modern2'

  def index
  end
end

app/controllers/modern3_controller.rb
class Modern3Controller < ApplicationController
  # レイアウトはmodern2と共有
  layout 'modern2'

  def index
  end
end

app/controllers/modern4_controller.rb
class Modern4Controller < ApplicationController
  layout 'modern4'

  def index
  end
end

app/controllers/modern5_controller.rb
class Modern5Controller < ApplicationController
  layout 'modern5'

  def index
  end
end

app/controllers/modern6_controller.rb
class Modern6Controller < ApplicationController
  layout 'modern6'
  def index
  end
end

app/controllers/modern_controller.rb
class ModernController < ApplicationController
  layout 'modern'

  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/traditional_controller.rb
class TraditionalController < ApplicationController
  layout 'traditional'

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/modern2_helper.rb
module Modern2Helper
end

app/helpers/modern3_helper.rb
module Modern3Helper
end

app/helpers/modern4_helper.rb
module Modern4Helper
end

app/helpers/modern5_helper.rb
module Modern5Helper
end

app/helpers/modern6_helper.rb
module Modern6Helper
end

app/helpers/modern_helper.rb
module ModernHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/traditional_helper.rb
module TraditionalHelper
end

app/views/grid/index.html.erb
<div class="container">
  <div class="row">
    ※このページは以下のファイルから構成されています。ソースコードも参考にしつつ眺めてみて下さい。
    <ul>
      <li>コントローラ: app/controllers/grid_controller.rb</li>
      <li>ビュー
        <ul>
          <li>app/views/layouts/grid.html.erb</li>
          <li>app/views/grid/index.html.erb</li>
        </ul>
      </li>
      <li>その他
        <ul>
          <li>ルーティング: config/routes.rbの「get 'grid/index'」</li>
        </ul>
      </li>
    </ul>
  </div>

  <div class="row">
    <h1>段組レイアウト編</h1>
  </div>

  <div class="row" style="background-color: #ddd;">
    <p>
      Bootstrapのグリッドレイアウトは基本はCSSのrowクラス、col系クラスを使って配置を行う。
      必ずrowの中にcolを作っていくこと。
      また、<strong>rowを組むよりも外側をcontainerクラスを持つ要素で囲むこと</strong>
    </p>

    <p>
      例として、このグレーのブロックはdiv.rowの中に直接書かれた要素である。
    </p>

    <p>
      row（行）の中を分割したい場合に、div.row要素の中にdiv.col系クラスを使って記述していく。
      col（列）の基本は <strong>1つのrowの中を12分割</strong> である。
      以下の緑色ブロックはrowの中にcol-xs-1クラスの要素を12個並べたものである（ソースコードも見てみると分かりやすい）。ブロックの境目が分かりやすい様に便宜上borderを指定している。
    </p>
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #00ff00;">
    <div class="col-xs-1" style="border: solid 1px #00aa00;">1個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">2個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">3個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">4個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">5個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">6個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">7個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">8個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">9個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">10個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">11個目</div>
    <div class="col-xs-1" style="border: solid 1px #00aa00;">12個目</div>
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #ddd;">
    これを利用して、例えば3/12サイズの左サイドメニューと9/12サイズのコンテンツエリアがある様なページを作りたい場合、rowの中にcol-xs-3、col-xs-9を使い、以下の様な配置になる。
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #aaaaff;">
    <div class="col-xs-3" style="border: solid 1px #0000aa;">サイドメニュー</div>
    <div class="col-xs-9" style="border: solid 1px #0000aa;">（コンテンツエリア）
      <h1>タイトル</h1>
      <p>文章やコンテンツを書いていく</p>
    </div>
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #ddd;">
    右側にサイドメニューを置きたければ、先にコンテンツエリアを書けば良い
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #aaaaff;">
    <div class="col-xs-9" style="border: solid 1px #0000aa;">（コンテンツエリア）
      <h1>タイトル</h1>
      <p>文章やコンテンツを書いていく</p>
    </div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">サイドメニュー</div>
  </div>

  <div class="row">
    <h1>タイル状配置編</h1>
  </div>

  <div class="row" style="background-color: #ddd;">
    row内でcol要素を配置していくとき、12を超えた要素は次の行に回り込んでいく。これを利用するとタイル状に要素を配置することが簡単にできる（画像や動画のサムネイル一覧のイメージ）
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #ffaaaa;">
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素1</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素2</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素3</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素4</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素5</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素6</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素7</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素8</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素9</div>
    <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素10</div>
  </div>

  <div class="row">
    <h1>タイル状配置編</h1>
  </div>

  <div class="row" style="background-color: #ddd;">
    row内でcol要素を配置していくとき、12を超えた要素は次の行に回り込んでいく。これを利用するとタイル状に要素を配置することが簡単にできる（画像や動画のサムネイル一覧のイメージ）
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row">
    <h1>まとめ</h1>
  </div>

  <div class="row" style="background-color: #ddd;">
    colの中にrowを書くこともできるので、Youtubeの様に「サイドメニュー＋コンテンツエリアにタイル状に要素を配置」と言ったことは以下の様なコードで実現できる（具体的なソースはファイルを見ること）
  </div>

  <div class="row" style="height: 10px;"></div>

  <div class="row" style="background-color: #ff88ff;">
    ヘッダ
  </div>
  <div class="row" style="background-color: #ffaaaa;">
    <div class="col-xs-3" style="background-color: #88ff88;">
      サイドメニュー
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    </div>
    <div class="col-xs-9" style="background-color: #ffaaaa;">
      <div class="row" style="border: solid 1px #aa0000;">
        <h1>メインコンテンツエリア</h1>
      </div>
      <div class="row">
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素1</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素2</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素3</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素4</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素5</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素6</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素7</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素8</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素9</div>
        <div class="col-xs-3" style="border: solid 1px #0000aa;">col-xs-3の要素10</div>
      </div>
    </div>
  </div>
  <div class="row" style="background-color: #8888ff;">
    フッタ
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yuusukehp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/grid.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ズルいゆうすけブログ！</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'modern', media: 'all' %>
  <%= stylesheet_link_tag controller_name, media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id="nav-header" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-home"></span>
        ゆうすけのブログ
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="#">最新の日記</a></li>
        <li><a href="#">過去の日記</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<div id="main-content">
  <%= yield %>
</div>

<hr/>
<footer>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      &copy; ゆうすけ, 2014

    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/modern.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>いまどきのゆうすけブログ！</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'modern', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>ゆうすけのブログ</h1>
<hr/>
メニュー：
<a href="#">About</a>｜
<a href="#">最新の日記</a>｜
<a href="#">過去の日記</a>
<br/>
※ダミーリンクなのでクリックしても遷移しません
<hr/>

<%= yield %>

&copy; ゆうすけ, 2014

</body>
</html>

app/views/layouts/modern2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>いまどきのゆうすけブログ2！</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'modern', media: 'all' %>
  <%= stylesheet_link_tag controller_name, media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ゆうすけのブログ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="#">最新の日記</a></li>
        <li><a href="#">過去の日記</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<%= yield %>

<footer>
  &copy; ゆうすけ, 2014
</footer>

</body>
</html>

app/views/layouts/modern4.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>いまどきのゆうすけブログ2！</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'modern', media: 'all' %>
  <%= stylesheet_link_tag controller_name, media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ゆうすけのブログ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="#">最新の日記</a></li>
        <li><a href="#">過去の日記</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<%= yield %>

<footer>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      &copy; ゆうすけ, 2014

    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/modern5.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>いまどきのゆうすけブログ2！</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'modern', media: 'all' %>
  <%= stylesheet_link_tag controller_name, media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-home"></span>
        ゆうすけのブログ
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="#">最新の日記</a></li>
        <li><a href="#">過去の日記</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<%= yield %>

<footer>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      &copy; ゆうすけ, 2014

    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/modern6.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ズルいゆうすけブログ！</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'modern', media: 'all' %>
  <%= stylesheet_link_tag controller_name, media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'modern.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id="nav-header" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-home"></span>
        ゆうすけのブログ
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="#">最新の日記</a></li>
        <li><a href="#">過去の日記</a></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<div id="main-content">
  <%= yield %>
</div>

<hr/>
<footer>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      &copy; ゆうすけ, 2014

    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/traditional.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ゆうすけのブログ</title>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>ゆうすけのブログ</h1>
<hr/>
メニュー：
<a href="#">About</a>｜
<a href="#">最新の日記</a>｜
<a href="#">過去の日記</a>
<br/>
※ダミーリンクなのでクリックしても遷移しません
<hr/>
<%= yield %>

<hr/>
&copy; ゆうすけ, 2014

</body>
</html>

app/views/modern/index.html.erb
<h2>Bootstrapとかいうのを入れてみた</h2>
<p>
  見た目がダサいと周りからさんざん言われたので、Bootstrapとかいうのを入れてみた。
  どうやらこれを使うと
</p>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Bootstrap Panelのてすと（ここがpanel-heading）</h3>
  </div>
  <div class="panel-body">
    こういうパネル表示ができるみたい（ここはpanel-body）
  </div>
  <div class="panel-footer">Panelにはフッタも設定できるっぽい（ここはpanel-footer）</div>
</div>

<p>
  こういうことが簡単にできるらしい。
  このページはまだ既存のHTMLにBootstrapを適用しただけなのでまだ表示が怪しい。
  次はまるっとBootstrapの流儀に従って書き直さないといけないな。
</p>

<h2>今日の日記</h2>
<p>
  日記書き始めたけど書くことないな。みんな何書いてるんだろう？
</p>

<hr/>

<h2>ブログはじめました</h2>
<p>
  今ナウなヤングの中でブログを始めるのが流行ってるらしいので、はじめてみました
</p>

<hr/>

app/views/modern2/index.html.erb
<h2>Bootstrapに合わせてヘッダとフッタを修正してみた</h2>
<p>
  とりあえずレイアウトファイル（views/layout/modern2.html.erb）を修正し、ヘッダとフッタだけ差し替えしてみた。これでメニュー項目はそれなりにマシになった印象。
  次はコンテンツ部分（views/modern2/index.html.erb）を修正していこうと思う
</p>


<hr/>

<h2>Bootstrapとかいうのを入れてみた</h2>
<p>
  見た目がダサいと周りからさんざん言われたので、Bootstrapとかいうのを入れてみた。
  どうやらこれを使うと
</p>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Bootstrap Panelのてすと（ここがpanel-heading）</h3>
  </div>
  <div class="panel-body">
    こういうパネル表示ができるみたい（ここはpanel-body）
  </div>
  <div class="panel-footer">Panelにはフッタも設定できるっぽい（ここはpanel-footer）</div>
</div>

<p>
  こういうことが簡単にできるらしい。
  このページはまだ既存のHTMLにBootstrapを適用しただけなのでまだ表示が怪しい。
  次はまるっとBootstrapの流儀に従って書き直さないといけないな。
</p>

<h2>今日の日記</h2>
<p>
  日記書き始めたけど書くことないな。みんな何書いてるんだろう？
</p>

<hr/>

<h2>ブログはじめました</h2>
<p>
  今ナウなヤングの中でブログを始めるのが流行ってるらしいので、はじめてみました
</p>

<hr/>

app/views/modern3/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Bootstrapに合わせてコンテンツ部分を修正してみた</h2>
    <p>
      <a href="http://getbootstrap.com/css/#grid">BootstrapのGrid systemに関する説明</a>を見つつ、コンテンツ部分が横に広がり過ぎていたので左右に1/12の余白を設けるようにしてみた。
    </p>
    <p>
      一つ前の投稿にあるPanelなんかも、これで多少すっきりしたかな。
    </p>
  </div>
</div>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Bootstrapに合わせてヘッダとフッタを修正してみた</h2>
    <p>
      <a href="http://getbootstrap.com/components/#navbar">BootstrapのNavbarに関する説明</a>を見つつ、
      とりあえずレイアウトファイル（views/layout/modern2.html.erb）を修正し、ヘッダとフッタだけ差し替えしてみた。これでメニュー項目はそれなりにマシになった印象。
      次はコンテンツ部分（views/modern2/index.html.erb）を修正していこうと思う
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>Bootstrapとかいうのを入れてみた</h2>
    <p>
      見た目がダサいと周りからさんざん言われたので、Bootstrapとかいうのを入れてみた。
      どうやらこれを使うと
    </p>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Bootstrap Panelのてすと（ここがpanel-heading）</h3>
      </div>
      <div class="panel-body">
        こういうパネル表示ができるみたい（ここはpanel-body）
      </div>
      <div class="panel-footer">Panelにはフッタも設定できるっぽい（ここはpanel-footer）</div>
    </div>

    <p>
      こういうことが簡単にできるらしい。
      このページはまだ既存のHTMLにBootstrapを適用しただけなのでまだ表示が怪しい。
      次はまるっとBootstrapの流儀に従って書き直さないといけないな。
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>今日の日記</h2>
    <p>
      日記書き始めたけど書くことないな。みんな何書いてるんだろう？
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h2>ブログはじめました</h2>
    <p>
      今ナウなヤングの中でブログを始めるのが流行ってるらしいので、はじめてみました
    </p>
  </div>
</div>



<hr/>

app/views/modern6/_social_links.html.erb
<div class="control">
  <ul class="clearfix">
    <li>
      <%= date %>
    </li>
    <li>
      <a href="#">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        いいね！（10）
      </a>
    </li>
    <li>
      <a href="#">
        <span class="glyphicon glyphicon-pencil"></span>
        コメントする（0）
      </a>
    </li>
  </ul>
</div>

app/views/page/index.html.erb
<h1>モックサンプル集</h1>
<p>詳しくはソースをみましょう</p>
<hr/>
<ul>
  <li><%= link_to 'ショボいデザインの例（traditionalコントローラ）', traditional_index_path %></li>
  <li><%= link_to 'Bootstrapを導入した例（modernコントローラ）', modern_index_path %></li>
  <li><%= link_to 'Bootstrapを導入し、Bootstrapの流儀に従ってレイアウトファイルを書き直した例（modern2コントローラ）', modern2_index_path %></li>
  <li><%= link_to 'modern2にさらに追加でコンテンツ部分もBootstrap流儀に書き直した例（modern3コントローラ）', modern3_index_path %></li>
  <li><%= link_to 'modern3にさらに追加で自前スタイルを追加し、見た目を整えたバージョン（modern4コントローラ）', modern4_index_path %></li>
  <li><%= link_to 'modern4にWebフォントでアイコンをつけ、さらに見た目を整えたバージョン（modern5コントローラ）', modern5_index_path %></li>
  <li><%= link_to 'modern5をズルくしたバージョン（modern6コントローラ）', modern6_index_path %>
    <ul>
      <li>参考（ズルいデザイン）：<%= link_to 'zurui-design by ken_c_lo / TAEKO AKATSUKA', 'https://speakerdeck.com/ken_c_lo/zurui-design' %></li>
      <li>参考（背景素材）：<%= link_to 'Subtle Patterns', 'http://subtlepatterns.com/' %></li>
    </ul>
  </li>
  <li><%= link_to '段組（グリッド）レイアウトのサンプル', grid_index_path %></li>
</ul>

app/views/traditional/index.html.erb
<h2>今日の日記</h2>
<p>
  日記書き始めたけど書くことないな。みんな何書いてるんだろう？
</p>

<hr/>

<h2>ブログはじめました</h2>
<p>
  今ナウなヤングの中でブログを始めるのが流行ってるらしいので、はじめてみました
</p>